In [6]:
#Employee Class
class Employee:
    num_of_employees = 0

    #initializing the attributes
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_of_employees += 1

    #Average Salary Method
    def averageSalary(self, employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)
#Full Time Employee Class - Super Class
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, employment_type):
        super().__init__(name, family, salary, department)
        self.employment_type = employment_type

# Instances of Employee class
employee1 = Employee("Susmitha", "Bhimavarapu", 50000, "Senior Software")
employee2 = Employee("Agesh", "Reddy", 80000, "Manager")

# Instances of FulltimeEmployee class
fulltime1 = FulltimeEmployee("poojitha", "Kodati", 50000, "Engineering", "FullTime")
fulltime2 = FulltimeEmployee("Uma", "Annabathini", 60000, "Marketing", "PartTime")

# Call member functions
employees = [employee1, employee2, fulltime1, fulltime2]
avgSalary = employee1.averageSalary(employees)

print("Total Employees:", Employee.num_of_employees)
print("Average Salary:", avgSalary)

Total Employees: 4
Average Salary: 60000.0


Explanation of the Code
Employee Class:

Represents general employees with attributes like name, family, salary, and department.
Tracks the total number of employees using a class variable.
Includes a method to calculate the average salary of employees.
FulltimeEmployee Class:

Inherits from Employee and adds an attribute employment_type (e.g., Full-Time or Part-Time).
Instances:

Four employee objects are created (two Employee and two FulltimeEmployee).
Total employees are tracked, and the average salary is calculated using all instances.








In [5]:
import numpy as np
#generating a vector
vector = np.random.uniform(1, 20, 20)

#reshaping the vector into 4 * 5 matrix
matrix = vector.reshape(4, 5)

print("Original Matrix: \n",matrix)

#finding the index of the max element along axis = 1
indices = np.argmax(matrix, axis=1)

#Create a range of indices for each row
row_indices = np.arange(matrix.shape[0])

#Use advanced indexing to replace max values with 0
matrix[row_indices, indices] = 0

print("Resultant Matrix: \n",matrix)

Original Matrix: 
 [[16.80194325  6.70954138  4.03391974  5.48816689  8.78122246]
 [ 2.1913659   8.07141792 15.75142584 17.38504833  1.53285007]
 [16.45972896 14.79828153  8.53132349 16.40428575 10.11082012]
 [14.27552178  3.94385921 12.40042049 10.86932625  1.3544417 ]]
Resultant Matrix: 
 [[ 0.          6.70954138  4.03391974  5.48816689  8.78122246]
 [ 2.1913659   8.07141792 15.75142584  0.          1.53285007]
 [ 0.         14.79828153  8.53132349 16.40428575 10.11082012]
 [ 0.          3.94385921 12.40042049 10.86932625  1.3544417 ]]


Explanation:
Random Vector:

A vector of size 20 is generated with random floats in the range 1-20 using np.random.uniform.
Reshape:

The vector is reshaped into a 4x5 matrix using the .reshape() method.
Replace Max in Each Row:

The maximum value in each row is located using np.argmax(axis=1), which gives the column indices of the max values.
The np.arange function creates row indices to pair with the max column indices.
These indices are used to set the maximum values to 0 without a loop.
Let me know if you'd like further assistance!







